stages:
  - test

test:
  stage: test
  image: python:3.7.0-stretch
  script:
    - pip install -r requirements.txt
    - make test

lint:
  stage: test
  image: python:3.7.0-stretch
  script:
    - pip install -r requirements.txt
    - make lint
